services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - './.db/pg-15:/var/lib/postgresql/data'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build: .
    tty: true
    environment:
      SECRET_KEY: ${SECRET_KEY:-test}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST:-postgres}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME:-test}
      DJANGO_DB_USER: ${DJANGO_DB_USER:-test}
      DJANGO_DB_PASS: ${DJANGO_DB_PASS:-test}
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_data: