version: '3.10.9'

services:
  web:
    build: .
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes:
  postgres_data: