kind: ConfigMap
apiVersion: v1
metadata:
  # This name uniquely identifies the ConfigMap
  name: {{ template "django-backend-app.fullname" . }}-configmap
  labels:
    app: {{ template "django-backend-app.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  
data:
  DEBUG: {{ required "env.DEBUG" .Values.env.DEBUG | quote }}
  ENVIRONMENT: {{ required "env.ENVIRONMENT" .Values.env.ENVIRONMENT | quote }}
  ALLOWED_HOSTS: {{ required "env.ALLOWED_HOSTS" .Values.env.ALLOWED_HOSTS | quote }}

  # email
  DEFAULT_FROM_EMAIL: {{ required "env.DEFAULT_FROM_EMAIL" .Values.env.DEFAULT_FROM_EMAIL | quote }}