kind: Secret
apiVersion: v1
metadata:
  name: {{ template "django-backend-app.fullname" . }}-secret
  labels:
    app: {{ template "django-backend-app.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
data:
  # Secret key
  SECRET_KEY: {{ required "env.SECRET_KEY" .Values.env.SECRET_KEY | quote }}

  # Database
  DJANGO_DB_HOST: {{ required "env.DJANGO_DB_HOST" .Values.env.DJANGO_DB_HOST | quote }}
  DJANGO_DB_NAME: {{ required "env.DJANGO_DB_NAME" .Values.env.DJANGO_DB_NAME | quote }}
  DJANGO_DB_USER: {{ required "env.DJANGO_DB_USER" .Values.env.DJANGO_DB_USER | quote }}
  DJANGO_DB_PASS: {{ required "env.DJANGO_DB_PASS" .Values.env.DJANGO_DB_PASS | quote }}

  # Email
  EMAIL_HOST: {{ required "secrets.EMAIL_HOST" .Values.secrets.EMAIL_HOST | quote }}
  EMAIL_PORT: {{ required "secrets.EMAIL_PORT" .Values.secrets.EMAIL_PORT | quote }}
  EMAIL_HOST_USER: {{ required "secrets.EMAIL_HOST_USER" .Values.secrets.EMAIL_HOST_USER | quote }}
  EMAIL_HOST_PASSWORD: {{ required "secrets.EMAIL_HOST_PASSWORD" .Values.secrets.EMAIL_HOST_PASSWORD | quote }}