apiVersion: v2
name: django-backend-app
description: A Helm chart for django backend app
type: application
version: 0.1.0
appVersion: "1.16.0"

sources:
  - https://github.com/susilnem/docker-drf-postgresql-gunicorn-nginx.git

dependencies:
  - name: postgresql
    version: 15.5.32
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami